name: Discord Push Notification

on:
  push:
    branches: [ main, master, develop ]  # Add branches you want to monitor

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Discord notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "New Push to ${{ github.repository }}"
          description: |
            **Branch:** `${{ github.ref_name }}`
            **Commit:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.author.name }}
            
            [View Commit](${{ github.event.head_commit.url }})
          color: 0x00ff00
          username: "GitHub Bot"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
